### ISSUE TITLE
Bachelor Thesis

### ISSUE THREAD

**Issue by nicolaslimajf** [cotri/BEMT#2]
Hello, Cotri!

I am a PhD student at the Federal University of Juiz de Fora - Brazil. My area of concentration is CFD, performance and optimization, in particular propellers.
I tested the code you developed and I really liked it, congratulations! I would like to read your bachelor's thesis in aerospace engineering (I am also an aerospace engineer!). Could you send me, please?

Best regards,

Nícolas Lima Oliveira

**Comment by cotri** [comment]
Hi Nicolas,

Sorry for the inactivity, it has been a while.

First of all, I truly appreciate your comment and your interest in the work. The thesis, however, was not written in English, so that might be a problem.

Let me know if you still want it and I'll be more than happy to send it to you, otherwise I'll mark this issue as closed.

Again, sorry for the late response.

Best regards.


PD: I may also consider uploading the latex documents at some point if you or someone else may be interested in taking a look (translated, of course). Just let me know if that's the case and I will consider it if I have the time to do so.

**Comment by cotri** [comment]
This issue is now closed for being inactive.
