### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by bbu-0078** [cotri/BEMT#3]
Hey, I am unable to run your code due to some errors. Could you please guide me on that ? Thanks 
I am getting this error " Unrecognized function or variable 'linRange'. "

**Comment by cotri** [comment]
Hi bbu,

I appreciate your interest for this project. Just to make sure we are in the same page, the Matlab code for the BEMT tool is run from the _main.m_ which depends on:

- _init.m_: Matlab file that loads initial variables (mostly constants)
- _data_: contains polar ($C_L$ and $C_D$ vs AoA) and propeller geometry data
- _functions_: contains all the user-defined functions required to run the tool

These last two directories (_data_ and _functions_) need to be added to the Matlab _search path_ so that Matlab itself knows where to look for when running files outside the default search path.

Based on what you have told me, (if I am not mistaken) it seems that the _functions_ folder is not present in the search path causing the "unrecognized function" error when the code execution arrives at the first user-defined function "linRange".

Let me know if that was the case and if it solved your problem.

Next time, please, try to include the following:

- Brief and clear description of the issue you are experiencing
- What you were trying to do, the expected behavior and what happened instead
- A way to reproduce the behavior/error
- Any logs, error output, Matlab version used, screenshots, etc. would be useful too

**Comment by cotri** [comment]
This issue is now closed due to inactivity.
